# Generated by Django 4.1.7 on 2023-04-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(max_length=200)),
                ('Option1', models.CharField(max_length=50)),
                ('Option2', models.CharField(max_length=50)),
                ('Option3', models.CharField(max_length=50)),
                ('Option4', models.CharField(max_length=50)),
                ('CorrectOption', models.CharField(choices=[('None', 'None'), ('1', 'Option1'), ('2', 'Option2'), ('3', 'Option3'), ('4', 'Option4')], default='None', max_length=50)),
            ],
        ),
    ]
