# Generated by Django 4.1.7 on 2023-03-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Class', models.CharField(default='', max_length=5)),
                ('Section', models.CharField(default='', max_length=30)),
                ('Address', models.CharField(default='', max_length=50)),
                ('MobileNo', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
