# Generated by Django 4.1.7 on 2023-04-05 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_UserAccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
