# Generated by Django 4.2.4 on 2024-10-04 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklist',
            name='lastModify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('isCompleted', models.BooleanField(default=False)),
                ('priority', models.CharField(default='low', max_length=15)),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskList.tasklist')),
            ],
        ),
    ]
