# Generated by Django 4.2.4 on 2024-10-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0002_tasklist_created_tasklist_lastmodify_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('completed', 'Completed'), ('init', 'Init')], default='init', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TaskList.tasklist'),
        ),
    ]
