# Generated by Django 4.1.6 on 2023-02-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=30)),
                ('Dob', models.DateField()),
                ('Address', models.CharField(max_length=50)),
                ('MobileNo', models.CharField(max_length=10)),
            ],
        ),
    ]
