# Generated by Django 4.2.1 on 2023-06-02 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lastUpdatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserId_lastUpdatedBy', to=settings.AUTH_USER_MODEL)),
                ('registeredBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userId_registeredBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
