# Generated by Django 4.2.1 on 2023-06-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='partId',
        ),
    ]
