# Generated by Django 4.2.1 on 2023-06-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_parts_partid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
