# Generated by Django 4.2.3 on 2023-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Data_Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
