# Generated by Django 4.2.1 on 2023-05-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_Name', models.CharField(max_length=20)),
                ('student_FatherName', models.CharField(max_length=20)),
                ('student_City', models.CharField(max_length=20)),
                ('student_Class', models.IntegerField()),
                ('student_MobileNumber', models.IntegerField()),
                ('regDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
